### ISSUE TITLE
completed tutorial version

### ISSUE THREAD

**Issue by chroda** [christopher4lis/express-cc#2]
hello, do you have a tutorial completed version of this repo?

**Comment by mishatatinets** [comment]
You're right. That would be much appreciated.

**Comment by lyzs90** [comment]
just finished part 8 and have a fork [here](https://github.com/lyzs90/node-auth) if you guys are interested

**Comment by kimnthai** [comment]
unresolved issue with with webpack and extract-text-webpack-plugin

**Comment by christopher4lis** [comment]
Hey everyone, thanks for checking in here.

I've actually been working on a revamp of the entire course that uses an upgraded version of express-cc called [Voyager](https://github.com/chriscourses/voyager). You'll be able to create both the starting version of the repo and the end result using the new framework.

Trying my hardest to get things up and running, will close the issue once the new series / completed repo is released.

**Comment by Divya-12657** [comment]
I get a error as

GET / 304 99.638 ms - -
GET /login 304 20.118 ms - -
GET /login?username=Divyasree&password=jhflsjfd 200 19.987 ms - 7354

**Comment by Divya-12657** [comment]
pls can someone help me solve this i have written the same code as in the tutorial

**Comment by h3ct0rjs** [comment]
@divyasreevenkat Hi, hmmm can you show me your code. Maybe I can help you, 
actually I also have a question about serializing and deserializing the data but don't know if @christopher4lis  can help. 

When you create this couple of functions for the serializer it should be the same field name that you use in the mysql table ? actually I'm using id_user as my id field, but it always said that : 

> failed to serialize user into session
```js

 passport.serializeUser(function(user_id, done) {
        done(null, user_id);
    });

    passport.deserializeUser(function(user_id, done) {
        done(null, user_id);
    });

// and when I'm creating my user_id variable is 
const user_id = results[0];
```

**Comment by Divya-12657** [comment]
passport.use(new LocalStrategy(
  function(email, password, done){
    //username = email;
     console.log(email);
    console.log(password);
    const db = require('./db');
    connection.query('SELECT password FROM users WHERE email = ?',
[email],function(err,results,fields){
      if(err){console.log('query wrong');}
      if(results.length==0){
        done(null,false);
      }
      var new1=results[0].password;
      string.compare(password,new1,function(err,response){
        if(response==true){
          return done(null,{user_id:results[0].id});
        }
        else{
          return done(null,'fdjlz');
        }

      });
    })

  }
  ));


//the above code in the app.js for passportt

//the below code in index.js

router.get('/login',function(req, res){
res.render('login');
});

router.post('/login', passport.authenticate(
'local',{
successRedirect:  '/secret',
failureRedirect: '/login'
}
));

**Comment by Divya-12657** [comment]
should i make email  as the primary in my mysql.

**Comment by h3ct0rjs** [comment]
@divyasreevenkat Yeah I guess that would be your primary key, I would like to get the complete version of this code when would be that @christopher4lis

**Comment by Divya-12657** [comment]
I WILL SEND IT BYY TODAY

**Comment by Divya-12657** [comment]
I've shared an item with you:

myapp
https://drive.google.com/drive/folders/1VbUmvwvZYjfLfOy02WL2YcNHFT-2rH3V?usp=sharing&ts=5ae32261

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by chroda** [comment]
Hey dudes, I believe this issue has been out dated, right?
Can we close it? 😄 
**The current comments do not match the opening of the issue.**

@christopher4lis Thanks for your effort, I'll close this issue now, if you want, **reopen** please.

_Good code for all folks._
