### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kaizen1** [christopher4lis/express-cc#3]
Hi Christopher,
This is very helpful code. It would be great if you would add a license as Unlicense or MIT so we can use in a commercial project.
Thanks

**Comment by christopher4lis** [comment]
Hey there, thanks for the suggestion, I'll definitely be sure to add this in.

On a related note, I'd actually recommend checking out the new Node framework I've been working on called [Voyager](https://github.com/chriscourses/voyager), it has a lot of extra web-app development features and is much cleaner code-wise than the current express-cc repo. Still in progress, but the core foundation is there and ready for usage in dev.

This repo will eventually be deprecated once the updated Node Auth course is released. Thanks for the request!

**Comment by christopher4lis** [comment]
MIT license added.
